### ISSUE TITLE
SSH keys by name

### ISSUE THREAD

**Issue by cstrutton** [koalalorenzo/python-digitalocean#128]
I just came across this library and find it very well put together.  There is one feature I would like to see.  I would like to create a droplet referencing the ssh key by name.  I have several keys stored at DO and add one or several of them to each droplet I create.  Using the key name to reference the key just makes sense to me.  I will look into what it would take to do this.

**Comment by andrewsomething** [comment]
Just FYI, like Droplets, there is no guarantee that the name is unique for an SSH key. So if this is added, I'd recommend the function be be named something like "search" or "lookup" and return an array.

**Comment by koalalorenzo** [comment]
I agree, there is no guarantee that the name is unique. You can create an X amount of keys with the same name but different IDs.

@cstrutton, I don't think it is possible, because of this reason. If I have understood correctly, you would like to assign a droplet to a key by using its name. It makes sense to me, and maybe this is a cool feature to integrate in the next release, but we have to think about how to implement this to avoid the wrong key to be selected.

**Comment by cstrutton** [comment]
I didn't realise that names were not unique.  Returning an array makes sense.  This fits with my use case.  I still believe it needs to be done.  If i have to store the key to use it, there is no advantage to storing a key with DO.

**Comment by koalalorenzo** [comment]
Note: You store a public key on Digital Ocean. Not the private key. I am not sure if this is really a required feature: the most of the methods/classes/functions provided by python-digitalocean are a direct interface to DO's API. Any other "functionality" may require more code and better logic... which may be integrated in a future version of this library.
