### ISSUE TITLE
Power off droplet automaticly before attempting droplet.take_snapshot()

### ISSUE THREAD

**Issue by corndogcomputers** [koalalorenzo/python-digitalocean#98]
SInce the droplet snapshot requires the droplet to be off before it can create a snapshot, why not add that in the take_snapshot function? 

This would allow us to create a snapshot without first having to check it's status, power it off, and wait for the action to complete before then calling the take_snapshot function separately.

Am I off the mark on this? What are your thoughts?

**Comment by koalalorenzo** [comment]
The best to do this is to enable with a method. I think that the closer to the API we are, the better the developers will understand how this library is working: Instead of reading several documentation (that probably is required) they should just understand how DO APIs are working, and directly use python-digitalocean.

Anyway, it is a good point :+1: Probably I will implement this in the next release (Monday or Sunday): an option that will shut down the machine and take the snapshot.

**Comment by corndogcomputers** [comment]
Makes perfect sense. Thanks!
